import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Bootstrap
import "bootstrap/dist/css/bootstrap.min.css";
import 'bootstrap-icons/font/bootstrap-icons.css';

// Componentes
import Navbar from '@/components/blocks/Navbar'
import Footer from "@/components/blocks/Footer";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="pt-br">
            {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossOrigin="anonymous"></link> */}

            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Navbar />

                {children}

                <Footer />


                {/* Container para os toast */}
                <div
                    id="toastContainer"
                    className="toast-container position-fixed bottom-0 end-0 p-3"
                    style={{ zIndex: 1055 }}
                ></div>

                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossOrigin="anonymous"></script>
            </body>
        </html>
    );
}
